#!/usr/bin/env bash
# lessfilter to use pygmentize

[[ -n $(command -v pygmentize) ]] || exit 1

case "$1" in
    # add all extensions you want to handle here
    *.awk|*.groff|*.java|*.js|*.m4|*.php|*.pl|*.pm|*.pod|*.sh|\
    *.ad[asb]|*.asm|*.inc|*.[ch]|*.[ch]pp|*.[ch]xx|*.cc|*.hh|\
    *.lsp|*.l|*.pas|*.p|*.xml|*.xps|*.xsl|*.axp|*.ppd|*.pov|\
    *.diff|*.patch|*.py|*.rb|*.sql|*.ebuild|*.eclass)
        pygmentize "$1"
        exit 0
        ;;
esac

# Types that pygmentize didn't support at time of writing
#text/x-gawk, text/x-nawk, text/x-awk, text/x-asm, text/x-bcpl,
#text/x-m4, text/x-pl1

# add all MIME types you want to handle here
case "$(file --mime-type --brief --dereference --uncompress "$1")" in
    "application/xml"|"image/svg+xml") lexer="xml" ;;
    "text/html") lexer="html" ;;
    "text/troff") lexer="nroff" ;;
    "text/x-c") lexer="c" ;;
    "text/x-c++") lexer="cpp" ;;
    "text/x-diff") lexer="diff" ;;
    "text/x-java") lexer="java" ;;
    "text/x-lua") lexer="lua" ;;
    "text/x-makefile") lexer="make" ;;
    "text/x-msdos-batch") lexer="bat" ;;
    "text/x-pascal") lexer="pascal" ;;
    "text/x-perl") lexer="perl" ;;
    "text/x-po") lexer="po" ;;
    "text/x-python") lexer="python" ;;
    "text/x-shellscript") lexer="sh" ;;
    "text/x-tex") lexer="latex" ;;
esac

if [[ -z $lexer ]]; then
    case "$(head -n 1 "$1")" in
        *perl*) lexer="perl" ;;
        *python*) lexer="python" ;;
        *ruby*) lexer="ruby" ;;
        *sh*) lexer="sh" ;;
    esac
fi

[[ -n $lexer ]] || pygmentize -g "$1"
[[ -z $lexer ]] || pygmentize -l "$lexer" "$1"
