#!/usr/bin/env bash

[[ -n $(command -v ctags) ]] || exit

dir="$(git rev-parse --git-dir)"
trap "rm -f $dir/$$.tags" EXIT
git ls-files | ctags -L - -f $dir/$$.tags --languages=-javascript,sql
mv $dir/$$.tags $dir/tags
