#!/usr/bin/env bash

[[ -n $(command -v ctags) ]] || exit

# shellcheck disable=SC2064
trap "rm -f .$$.tags" EXIT

git ls-files | ctags -f .$$.tags -L - \
    --languages=-javascript,sql --tag-relative
mv ".$$.tags" .tags
