#!/usr/bin/env bash

# Capslock is Mod4
xmodmap -e "remove lock = Caps_Lock"
xmodmap -e "add mod4 = Caps_Lock"
xmodmap -e "keysym Caps_Lock = Super_L"

## Compositing
if [[ -n "$(command -v picom)" ]]; then
    if [[ ! -f "$HOME/.config/picom.conf" ]]; then
        cp /etc/xdg/picom.conf "$HOME/.config/"
    fi
    picom -b
fi

# Numlock
[[ -z "$(command -v numlockx)" ]] || numlockx on &

# PCManFM is run in daemon-mode to enable auto-mounting of removable
# media
[[ -z "$(command -v pcmanfm)" ]] || pcmanfm -d &
[[ -z "$(command -v pcmanfm-qt)" ]] || pcmanfm-qt -d &

sleep 10

# Flameshot
[[ -z "$(command -v flameshot)" ]] || flameshot &

# Local autostart script
[[ ! -f $HOME/.autostart.local ]] || "$HOME/.autostart.local"
